version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node:v0.16.0
    ports:
      - '${MOSAIC_GRAPH_RPC_PORT}:8000'
      - '${MOSAIC_GRAPH_WS_PORT}:8001'
      - '${MOSAIC_GRAPH_RPC_ADMIN_PORT}:8020'
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres:5432
      postgres_user: '${MOSAIC_POSTGRES_USER}'
      postgres_pass: '${MOSAIC_POSTGRES_PASSWORD}'
      postgres_db: '${MOSAIC_POSTGRES_DATABASE}'
      ipfs: 'ipfs:5001'
      ethereum: 'dev:http://${MOSAIC_GRAPH_NODE_HOST}:${MOSAIC_ETHEREUM_RPC_PORT}'
      RUST_LOG: info
      GRAPH_LOG: info
      ETHEREUM_POLLING_INTERVAL: 3000
      ETHEREUM_REORG_THRESHOLD: 0
  ipfs:
    image: ipfs/go-ipfs:v0.4.22-rc1
    ports:
      - '${MOSAIC_GRAPH_IPFS_PORT}:5001'
    volumes:
      - '${MOSAIC_GRAPH_DATA_FOLDER}/ipfs:/data/ipfs'
  postgres:
    image: postgres:alpine
    ports:
      - '${MOSAIC_POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: '${MOSAIC_POSTGRES_USER}'
      POSTGRES_PASSWORD: '${MOSAIC_POSTGRES_PASSWORD}'
      POSTGRES_DB: '${MOSAIC_POSTGRES_DATABASE}'
    volumes:
      - '${MOSAIC_GRAPH_DATA_FOLDER}/postgres:/var/lib/postgresql/data'
